server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: upload
          uri: http://localhost:8081
          predicates:
            - Path=/filelayoutids/**, 
        - id: index
          uri: http://localhost:8082
          predicates:
            - Path=/indexinformations/**, 
        - id: streamming
          uri: http://localhost:8083
          predicates:
            - Path=/indices/**, 
        - id: notify
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: display
          uri: http://localhost:8085
          predicates:
            - Path=, /dsshBoarves/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: upload
          uri: http://upload:8080
          predicates:
            - Path=/filelayoutids/**, 
        - id: index
          uri: http://index:8080
          predicates:
            - Path=/indexinformations/**, 
        - id: streamming
          uri: http://streamming:8080
          predicates:
            - Path=/indices/**, 
        - id: notify
          uri: http://notify:8080
          predicates:
            - Path=, 
        - id: display
          uri: http://display:8080
          predicates:
            - Path=, /dsshBoarves/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
